#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0.3 effective-5.10 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)
#ifndef PREBIDMOBILEUNITY_SWIFT_H
#define PREBIDMOBILEUNITY_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import PrebidMobile;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="PrebidMobileUnity",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSString;
@class AuctionResult;
@class NSDictionary;

SWIFT_CLASS("_TtC17PrebidMobileUnity6AdInfo")
@interface AdInfo : NSObject
@property (nonatomic, copy) NSString * _Nonnull adUnitId;
@property (nonatomic, copy) NSString * _Nonnull adFormat;
- (void)setAuctionResult:(AuctionResult * _Nullable)auctionResult;
- (NSDictionary * _Nonnull)toDictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIView;
@class UIViewController;

SWIFT_PROTOCOL("_TtP17PrebidMobileUnity10AdListener_")
@protocol AdListener <NSObject>
- (void)onAdLoadedWithAdInfo:(AdInfo * _Nonnull)adInfo;
- (void)onAdFailedWithAdInfo:(AdInfo * _Nonnull)adInfo error:(NSError * _Nonnull)error;
- (void)onAdDisplayedWithAdInfo:(AdInfo * _Nonnull)adInfo;
- (void)onAdClickedWithAdInfo:(AdInfo * _Nonnull)adInfo;
- (void)onAdClosedWithAdInfo:(AdInfo * _Nonnull)adInfo;
- (UIViewController * _Nullable)viewControllerForModalPresentationFromDisplayView:(UIView * _Nonnull)fromDisplayView SWIFT_WARN_UNUSED_RESULT;
@end

@class ErrorInfo;

SWIFT_PROTOCOL("_TtP17PrebidMobileUnity17AdRequestListener_")
@protocol AdRequestListener <NSObject>
- (void)onRequestSuccessWithAuctionResult:(AuctionResult * _Nonnull)auctionResult;
- (void)onRequestFailedWithAdUnitId:(NSString * _Nonnull)adUnitId errorInfo:(ErrorInfo * _Nonnull)errorInfo;
@end


SWIFT_CLASS("_TtC17PrebidMobileUnity13AuctionResult")
@interface AuctionResult : NSObject
- (NSDictionary * _Nonnull)toDictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17PrebidMobileUnity9ErrorInfo")
@interface ErrorInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull errMsg;
- (NSDictionary * _Nonnull)toDictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class AdUnitConfig;
@class NSCoder;
@protocol PluginEventDelegate;

SWIFT_CLASS("_TtC17PrebidMobileUnity13KnxBannerView")
@interface KnxBannerView : UIView <DisplayViewInteractionDelegate, DisplayViewLoadingDelegate>
/// The ad unit configuration.
@property (nonatomic, readonly, strong) AdUnitConfig * _Nonnull adUnitConfig;
/// ID of Stored Impression on the Prebid server
@property (nonatomic, readonly, copy) NSString * _Nonnull configID;
- (void)setImpExtraParams:(NSString * _Nonnull)key :(id _Nonnull)value;
- (NSDictionary<NSString *, id> * _Nonnull)getImpExtraParams SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, weak) id <AdListener> _Nullable adListener;
@property (nonatomic, weak) id <AdRequestListener> _Nullable adRequestListener;
/// Initializes a new <code>KnxBannerView</code>.
/// \param configID The configuration ID for the ad unit.
///
/// \param adSize The size of the ad.
///
- (nonnull instancetype)initWithConfigID:(NSString * _Nonnull)configID adSize:(CGSize)adSize;
- (nonnull instancetype)initWithFrame:(CGRect)frame configID:(NSString * _Nonnull)configID adSize:(CGSize)adSize OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)destroy;
/// Loads the ad for the banner view.
- (void)loadAd;
- (BOOL)canShow SWIFT_WARN_UNUSED_RESULT;
- (void)showAd;
/// Subscribe to plugin renderer events
- (void)setPluginEventDelegate:(id <PluginEventDelegate> _Nonnull)pluginEventDelegate;
- (void)displayViewDidLoadAd:(UIView * _Nonnull)displayView;
- (void)displayView:(UIView * _Nonnull)displayView didFailWithError:(NSError * _Nonnull)error;
- (void)trackImpressionForDisplayView:(UIView * _Nonnull)forDisplayView;
- (UIViewController * _Nullable)viewControllerForModalPresentationFromDisplayView:(UIView * _Nonnull)fromDisplayView SWIFT_WARN_UNUSED_RESULT;
- (void)didLeaveAppFrom:(UIView * _Nonnull)displayView;
- (void)willPresentModalFrom:(UIView * _Nonnull)displayView;
- (void)didDismissModalFrom:(UIView * _Nonnull)displayView;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@protocol InterstitialEventLoadingDelegate;
@protocol InterstitialEventInteractionDelegate;
@class BidResponse;

SWIFT_CLASS("_TtC17PrebidMobileUnity27KnxInterstitialEventHandler")
@interface KnxInterstitialEventHandler : NSObject <InterstitialEventHandlerProtocol>
@property (nonatomic, weak) id <InterstitialEventLoadingDelegate> _Nullable loadingDelegate;
@property (nonatomic, weak) id <InterstitialEventInteractionDelegate> _Nullable interactionDelegate;
@property (nonatomic, weak) id <AdRequestListener> _Nullable adRequestListener;
@property (nonatomic, copy) NSString * _Nonnull adUnitId;
- (nonnull instancetype)initWithAdUnitId:(NSString * _Nonnull)adUnitId OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) BOOL isReady;
- (void)showFromViewController:(UIViewController * _Nullable)controller;
- (void)requestAdWithBidResponse:(BidResponse * _Nullable)bidResponse;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol PBMPrimaryAdRequesterProtocol;
@class AdFormat;

/// Represents an interstitial ad unit. Built for rendering type of integration.
SWIFT_CLASS("_TtC17PrebidMobileUnity22KnxInterstitialManager")
@interface KnxInterstitialManager : NSObject
@property (nonatomic, weak) id <PBMPrimaryAdRequesterProtocol> _Nullable eventHandler;
@property (nonatomic, weak) id <AdListener> _Nullable adListener;
@property (nonatomic, weak) id <AdRequestListener> _Nullable adRequestListener;
/// The set of ad formats supported by this ad unit.
@property (nonatomic, copy) NSSet<AdFormat *> * _Nonnull adFormats;
- (void)setImpExtraParams:(NSString * _Nonnull)key :(id _Nonnull)value;
- (NSDictionary<NSString *, id> * _Nonnull)getImpExtraParams SWIFT_WARN_UNUSED_RESULT;
- (void)destroy;
- (void)loadAd;
- (void)showAdFrom:(UIViewController * _Nonnull)controller;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class InterstitialRenderingAdUnit;

@interface KnxInterstitialManager (SWIFT_EXTENSION(PrebidMobileUnity)) <InterstitialAdUnitDelegate>
/// Called when an ad is loaded and ready for display
- (void)interstitialDidReceiveAd:(InterstitialRenderingAdUnit * _Nonnull)interstitial;
/// Called when the load process fails to produce a viable ad
- (void)interstitial:(InterstitialRenderingAdUnit * _Nonnull)interstitial didFailToReceiveAdWithError:(NSError * _Nullable)error;
/// Called when the interstitial view will be launched,  as a result of show() method.
- (void)interstitialWillPresentAd:(InterstitialRenderingAdUnit * _Nonnull)interstitial;
/// Called when the interstitial is dismissed by the user
- (void)interstitialDidDismissAd:(InterstitialRenderingAdUnit * _Nonnull)interstitial;
/// Called when an ad causes the sdk to leave the app
- (void)interstitialWillLeaveApplication:(InterstitialRenderingAdUnit * _Nonnull)interstitial;
/// Called when user clicked the ad
- (void)interstitialDidClickAd:(InterstitialRenderingAdUnit * _Nonnull)interstitial;
@end

@protocol RewardedEventInteractionDelegate;

SWIFT_CLASS("_TtC17PrebidMobileUnity23KnxRewardedEventHandler")
@interface KnxRewardedEventHandler : NSObject <RewardedEventHandlerProtocol>
@property (nonatomic, weak) id <InterstitialEventLoadingDelegate> _Nullable loadingDelegate;
@property (nonatomic, weak) id <RewardedEventInteractionDelegate> _Nullable interactionDelegate;
@property (nonatomic, readonly) BOOL isReady;
- (void)showFromViewController:(UIViewController * _Nullable)controller;
- (void)requestAdWithBidResponse:(BidResponse * _Nullable)bidResponse;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol RewardedAdListener;

/// Represents an rewarded ad unit. Built for rendering type of integration.
SWIFT_CLASS("_TtC17PrebidMobileUnity18KnxRewardedManager")
@interface KnxRewardedManager : NSObject
/// A delegate for handling interactions with the ad unit.
@property (nonatomic, weak) id <PBMPrimaryAdRequesterProtocol> _Nullable eventHandler;
@property (nonatomic, weak) id <RewardedAdListener> _Nullable adListener;
@property (nonatomic, weak) id <AdRequestListener> _Nullable adRequestListener;
/// A Boolean value indicating whether the ad unit is ready to be displayed.
@property (nonatomic, readonly) BOOL isReady;
/// The set of ad formats supported by this ad unit.
@property (nonatomic, copy) NSSet<AdFormat *> * _Nonnull adFormats;
- (void)setImpExtraParams:(NSString * _Nonnull)key :(id _Nonnull)value;
- (NSDictionary<NSString *, id> * _Nonnull)getImpExtraParams SWIFT_WARN_UNUSED_RESULT;
- (void)destroy;
/// Loads a new ad.
- (void)loadAd;
/// Shows the ad from a specified view controller.
/// note:
/// This method must be called on the main thread.
/// \param controller The view controller from which the ad will be presented.
///
- (void)showFrom:(UIViewController * _Nonnull)controller;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class RewardedAdUnit;
@class PrebidReward;

@interface KnxRewardedManager (SWIFT_EXTENSION(PrebidMobileUnity)) <RewardedAdUnitDelegate>
/// Called when an ad is loaded and ready for display
- (void)rewardedAdDidReceiveAd:(RewardedAdUnit * _Nonnull)rewardedAd;
/// Called when user is able to receive a reward from the app
- (void)rewardedAdUserDidEarnReward:(RewardedAdUnit * _Nonnull)rewardedAd reward:(PrebidReward * _Nonnull)reward;
/// Called when the load process fails to produce a viable ad
- (void)rewardedAd:(RewardedAdUnit * _Nonnull)rewardedAd didFailToReceiveAdWithError:(NSError * _Nullable)error;
/// Called when the interstitial view will be launched,  as a result of show() method.
- (void)rewardedAdWillPresentAd:(RewardedAdUnit * _Nonnull)rewardedAd;
/// Called when the interstial is dismissed by the user
- (void)rewardedAdDidDismissAd:(RewardedAdUnit * _Nonnull)rewardedAd;
/// Called when an ad causes the sdk to leave the app
- (void)rewardedAdWillLeaveApplication:(RewardedAdUnit * _Nonnull)rewardedAd;
/// Called when user clicked the ad
- (void)rewardedAdDidClickAd:(RewardedAdUnit * _Nonnull)rewardedAd;
@end


SWIFT_PROTOCOL("_TtP17PrebidMobileUnity18RewardedAdListener_")
@protocol RewardedAdListener <AdListener>
- (void)onUserEarnedRewardWithAdInfo:(AdInfo * _Nonnull)adInfo reward:(PrebidReward * _Nullable)reward;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.0.3 effective-5.10 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)
#ifndef PREBIDMOBILEUNITY_SWIFT_H
#define PREBIDMOBILEUNITY_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import PrebidMobile;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="PrebidMobileUnity",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSString;
@class AuctionResult;
@class NSDictionary;

SWIFT_CLASS("_TtC17PrebidMobileUnity6AdInfo")
@interface AdInfo : NSObject
@property (nonatomic, copy) NSString * _Nonnull adUnitId;
@property (nonatomic, copy) NSString * _Nonnull adFormat;
- (void)setAuctionResult:(AuctionResult * _Nullable)auctionResult;
- (NSDictionary * _Nonnull)toDictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIView;
@class UIViewController;

SWIFT_PROTOCOL("_TtP17PrebidMobileUnity10AdListener_")
@protocol AdListener <NSObject>
- (void)onAdLoadedWithAdInfo:(AdInfo * _Nonnull)adInfo;
- (void)onAdFailedWithAdInfo:(AdInfo * _Nonnull)adInfo error:(NSError * _Nonnull)error;
- (void)onAdDisplayedWithAdInfo:(AdInfo * _Nonnull)adInfo;
- (void)onAdClickedWithAdInfo:(AdInfo * _Nonnull)adInfo;
- (void)onAdClosedWithAdInfo:(AdInfo * _Nonnull)adInfo;
- (UIViewController * _Nullable)viewControllerForModalPresentationFromDisplayView:(UIView * _Nonnull)fromDisplayView SWIFT_WARN_UNUSED_RESULT;
@end

@class ErrorInfo;

SWIFT_PROTOCOL("_TtP17PrebidMobileUnity17AdRequestListener_")
@protocol AdRequestListener <NSObject>
- (void)onRequestSuccessWithAuctionResult:(AuctionResult * _Nonnull)auctionResult;
- (void)onRequestFailedWithAdUnitId:(NSString * _Nonnull)adUnitId errorInfo:(ErrorInfo * _Nonnull)errorInfo;
@end


SWIFT_CLASS("_TtC17PrebidMobileUnity13AuctionResult")
@interface AuctionResult : NSObject
- (NSDictionary * _Nonnull)toDictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17PrebidMobileUnity9ErrorInfo")
@interface ErrorInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull errMsg;
- (NSDictionary * _Nonnull)toDictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class AdUnitConfig;
@class NSCoder;
@protocol PluginEventDelegate;

SWIFT_CLASS("_TtC17PrebidMobileUnity13KnxBannerView")
@interface KnxBannerView : UIView <DisplayViewInteractionDelegate, DisplayViewLoadingDelegate>
/// The ad unit configuration.
@property (nonatomic, readonly, strong) AdUnitConfig * _Nonnull adUnitConfig;
/// ID of Stored Impression on the Prebid server
@property (nonatomic, readonly, copy) NSString * _Nonnull configID;
- (void)setImpExtraParams:(NSString * _Nonnull)key :(id _Nonnull)value;
- (NSDictionary<NSString *, id> * _Nonnull)getImpExtraParams SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, weak) id <AdListener> _Nullable adListener;
@property (nonatomic, weak) id <AdRequestListener> _Nullable adRequestListener;
/// Initializes a new <code>KnxBannerView</code>.
/// \param configID The configuration ID for the ad unit.
///
/// \param adSize The size of the ad.
///
- (nonnull instancetype)initWithConfigID:(NSString * _Nonnull)configID adSize:(CGSize)adSize;
- (nonnull instancetype)initWithFrame:(CGRect)frame configID:(NSString * _Nonnull)configID adSize:(CGSize)adSize OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)destroy;
/// Loads the ad for the banner view.
- (void)loadAd;
- (BOOL)canShow SWIFT_WARN_UNUSED_RESULT;
- (void)showAd;
/// Subscribe to plugin renderer events
- (void)setPluginEventDelegate:(id <PluginEventDelegate> _Nonnull)pluginEventDelegate;
- (void)displayViewDidLoadAd:(UIView * _Nonnull)displayView;
- (void)displayView:(UIView * _Nonnull)displayView didFailWithError:(NSError * _Nonnull)error;
- (void)trackImpressionForDisplayView:(UIView * _Nonnull)forDisplayView;
- (UIViewController * _Nullable)viewControllerForModalPresentationFromDisplayView:(UIView * _Nonnull)fromDisplayView SWIFT_WARN_UNUSED_RESULT;
- (void)didLeaveAppFrom:(UIView * _Nonnull)displayView;
- (void)willPresentModalFrom:(UIView * _Nonnull)displayView;
- (void)didDismissModalFrom:(UIView * _Nonnull)displayView;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@protocol InterstitialEventLoadingDelegate;
@protocol InterstitialEventInteractionDelegate;
@class BidResponse;

SWIFT_CLASS("_TtC17PrebidMobileUnity27KnxInterstitialEventHandler")
@interface KnxInterstitialEventHandler : NSObject <InterstitialEventHandlerProtocol>
@property (nonatomic, weak) id <InterstitialEventLoadingDelegate> _Nullable loadingDelegate;
@property (nonatomic, weak) id <InterstitialEventInteractionDelegate> _Nullable interactionDelegate;
@property (nonatomic, weak) id <AdRequestListener> _Nullable adRequestListener;
@property (nonatomic, copy) NSString * _Nonnull adUnitId;
- (nonnull instancetype)initWithAdUnitId:(NSString * _Nonnull)adUnitId OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) BOOL isReady;
- (void)showFromViewController:(UIViewController * _Nullable)controller;
- (void)requestAdWithBidResponse:(BidResponse * _Nullable)bidResponse;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol PBMPrimaryAdRequesterProtocol;
@class AdFormat;

/// Represents an interstitial ad unit. Built for rendering type of integration.
SWIFT_CLASS("_TtC17PrebidMobileUnity22KnxInterstitialManager")
@interface KnxInterstitialManager : NSObject
@property (nonatomic, weak) id <PBMPrimaryAdRequesterProtocol> _Nullable eventHandler;
@property (nonatomic, weak) id <AdListener> _Nullable adListener;
@property (nonatomic, weak) id <AdRequestListener> _Nullable adRequestListener;
/// The set of ad formats supported by this ad unit.
@property (nonatomic, copy) NSSet<AdFormat *> * _Nonnull adFormats;
- (void)setImpExtraParams:(NSString * _Nonnull)key :(id _Nonnull)value;
- (NSDictionary<NSString *, id> * _Nonnull)getImpExtraParams SWIFT_WARN_UNUSED_RESULT;
- (void)destroy;
- (void)loadAd;
- (void)showAdFrom:(UIViewController * _Nonnull)controller;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class InterstitialRenderingAdUnit;

@interface KnxInterstitialManager (SWIFT_EXTENSION(PrebidMobileUnity)) <InterstitialAdUnitDelegate>
/// Called when an ad is loaded and ready for display
- (void)interstitialDidReceiveAd:(InterstitialRenderingAdUnit * _Nonnull)interstitial;
/// Called when the load process fails to produce a viable ad
- (void)interstitial:(InterstitialRenderingAdUnit * _Nonnull)interstitial didFailToReceiveAdWithError:(NSError * _Nullable)error;
/// Called when the interstitial view will be launched,  as a result of show() method.
- (void)interstitialWillPresentAd:(InterstitialRenderingAdUnit * _Nonnull)interstitial;
/// Called when the interstitial is dismissed by the user
- (void)interstitialDidDismissAd:(InterstitialRenderingAdUnit * _Nonnull)interstitial;
/// Called when an ad causes the sdk to leave the app
- (void)interstitialWillLeaveApplication:(InterstitialRenderingAdUnit * _Nonnull)interstitial;
/// Called when user clicked the ad
- (void)interstitialDidClickAd:(InterstitialRenderingAdUnit * _Nonnull)interstitial;
@end

@protocol RewardedEventInteractionDelegate;

SWIFT_CLASS("_TtC17PrebidMobileUnity23KnxRewardedEventHandler")
@interface KnxRewardedEventHandler : NSObject <RewardedEventHandlerProtocol>
@property (nonatomic, weak) id <InterstitialEventLoadingDelegate> _Nullable loadingDelegate;
@property (nonatomic, weak) id <RewardedEventInteractionDelegate> _Nullable interactionDelegate;
@property (nonatomic, readonly) BOOL isReady;
- (void)showFromViewController:(UIViewController * _Nullable)controller;
- (void)requestAdWithBidResponse:(BidResponse * _Nullable)bidResponse;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol RewardedAdListener;

/// Represents an rewarded ad unit. Built for rendering type of integration.
SWIFT_CLASS("_TtC17PrebidMobileUnity18KnxRewardedManager")
@interface KnxRewardedManager : NSObject
/// A delegate for handling interactions with the ad unit.
@property (nonatomic, weak) id <PBMPrimaryAdRequesterProtocol> _Nullable eventHandler;
@property (nonatomic, weak) id <RewardedAdListener> _Nullable adListener;
@property (nonatomic, weak) id <AdRequestListener> _Nullable adRequestListener;
/// A Boolean value indicating whether the ad unit is ready to be displayed.
@property (nonatomic, readonly) BOOL isReady;
/// The set of ad formats supported by this ad unit.
@property (nonatomic, copy) NSSet<AdFormat *> * _Nonnull adFormats;
- (void)setImpExtraParams:(NSString * _Nonnull)key :(id _Nonnull)value;
- (NSDictionary<NSString *, id> * _Nonnull)getImpExtraParams SWIFT_WARN_UNUSED_RESULT;
- (void)destroy;
/// Loads a new ad.
- (void)loadAd;
/// Shows the ad from a specified view controller.
/// note:
/// This method must be called on the main thread.
/// \param controller The view controller from which the ad will be presented.
///
- (void)showFrom:(UIViewController * _Nonnull)controller;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class RewardedAdUnit;
@class PrebidReward;

@interface KnxRewardedManager (SWIFT_EXTENSION(PrebidMobileUnity)) <RewardedAdUnitDelegate>
/// Called when an ad is loaded and ready for display
- (void)rewardedAdDidReceiveAd:(RewardedAdUnit * _Nonnull)rewardedAd;
/// Called when user is able to receive a reward from the app
- (void)rewardedAdUserDidEarnReward:(RewardedAdUnit * _Nonnull)rewardedAd reward:(PrebidReward * _Nonnull)reward;
/// Called when the load process fails to produce a viable ad
- (void)rewardedAd:(RewardedAdUnit * _Nonnull)rewardedAd didFailToReceiveAdWithError:(NSError * _Nullable)error;
/// Called when the interstitial view will be launched,  as a result of show() method.
- (void)rewardedAdWillPresentAd:(RewardedAdUnit * _Nonnull)rewardedAd;
/// Called when the interstial is dismissed by the user
- (void)rewardedAdDidDismissAd:(RewardedAdUnit * _Nonnull)rewardedAd;
/// Called when an ad causes the sdk to leave the app
- (void)rewardedAdWillLeaveApplication:(RewardedAdUnit * _Nonnull)rewardedAd;
/// Called when user clicked the ad
- (void)rewardedAdDidClickAd:(RewardedAdUnit * _Nonnull)rewardedAd;
@end


SWIFT_PROTOCOL("_TtP17PrebidMobileUnity18RewardedAdListener_")
@protocol RewardedAdListener <AdListener>
- (void)onUserEarnedRewardWithAdInfo:(AdInfo * _Nonnull)adInfo reward:(PrebidReward * _Nullable)reward;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
